
name: 'dbt_external_tables_integration_tests'
version: '1.0'

profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  require_generic_test_arguments_property: true

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt_external_tables_integration_tests', 'dbt_external_tables']

seeds:
  +quote_columns: false

models:
  dbt_external_tables_integration_tests:
    plugins:
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"

sources:
  dbt_external_tables_integration_tests:
    plugins:
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"

tests:
  dbt_external_tables_integration_tests:
    plugins:
      redshift:
        +enabled: "{{ target.type == 'redshift' }}"
      snowflake:
        +enabled: "{{ target.type == 'snowflake' }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' }}"
      spark:
        +enabled: "{{ target.type == 'spark' }}"
      synapse:
        +enabled: "{{ target.type == 'synapse' }}"
      azuresql:
        +enabled: "{{ target.type == 'sqlserver' }}"
